bugf-10-recherche-publication-affiche-undefined-et-user-nest-pas
teratany-social-network/frontend pull request #10
Opened 2023-12-09 08:25 UTC by Nyhasina23

bugf-10-recherche-publication-affiche-undefined-et-user-nest-pas

2023-12-09 18:25 UTC, MiandryRakoto requested changes
Rehefa mitady hoe ny hasina ohatra de tokony mahita eo am section ALL  ny result karazany rehetra, USER,PUBLICATION,PAGE, de ze tsy misy result atao hoe nothing... de za zao ra manao search hoe Ny hasina de user ihany no misy, tokony asina result ko nefa ao am publication...izay pub anle ny hasina
![1](https://github.com/teratany-social-network/frontend/assets/86937367/73d9897a-b50f-4bd0-983a-2d0627aaae4c)
![2](https://github.com/teratany-social-network/frontend/assets/86937367/acef1c3e-bd1c-49f9-b7cf-e2fd9f505e10)

2023-12-09 19:30 UTC, Nyhasina23 commented
Okayyy 👍

2023-12-14 18:32 UTC, andritianaa approved these changes

2023-12-14 18:33 UTC, andritianaa approved these changes

2023-12-14 18:33 UTC, merged