front-2-liste-des-profiles-followe-sur-le-feed
teratany-social-network/frontend pull request #8
Opened 2023-12-05 13:52 UTC by Nyhasina23

front-2-liste-des-profiles-followe-sur-le-feed

2023-12-05 14:02 UTC, andritianaa requested changes
## Ilay sary lasa fisaka, mila ampina object fit cover (voir le 2e profil)
![Screenshot_20231205-165845_Teratany](https://github.com/teratany-social-network/frontend/assets/50718030/8139031c-067f-49c1-9cf3-a4a787da5418)

## misy anle vue rehefa tsy mifollow profil mipotra kely rehefa mifindra ao amin'ny feed

2023-12-05 14:06 UTC, Nyhasina23 commented
Okok

2023-12-05 16:06 UTC, MiandryRakoto approved these changes
Somary tsy normal zany le sary sa ve hoe?
![Capture](https://github.com/teratany-social-network/frontend/assets/86937367/36e448fb-ffa3-4fac-8704-226291fe5ece)

2023-12-07 17:16 UTC, andritianaa approved these changes

2023-12-07 17:58 UTC, merged